[build]
  # Comando de build do Angular (pode ser npm ou yarn)
  command = "ng build --configuration production"
  # Pasta de sa√≠da do build (igual ao outputPath do angular.json)
  publish = "dist/academia"

[[redirects]]
  # Redirecionamento universal para o index.html (Angular SPA)
  from = "/*"
  to = "/index.html"
  status = 200
